package com.somesh.kvstore.cluster;

import java.io.BufferedReader;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.UncheckedIOException;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Client-side cluster router: routes a command to the shard that owns the key.
 *
 * <h2>MOVED protocol</h2>
 * Redis Cluster uses a MOVED redirect when a node receives a key it doesn't own
 * (e.g. a stale client connecting directly to the wrong shard). The response is:
 * <pre>
 *   -MOVED &lt;nodeId&gt; &lt;host&gt;:&lt;port&gt;
 * </pre>
 * This router itself is transparent — it silently forwards to the correct node.
 * The MOVED response is generated by {@link #movedResponse} and emitted by
 * per-node handlers when a client bypasses this router and hits the wrong shard
 * directly.
 *
 * <h2>Connection pooling</h2>
 * One persistent TCP connection is maintained per target node. Connections are
 * created on first use and reused for subsequent requests. This is a simple
 * connection-per-node model — a production system would use a proper connection
 * pool with health checks and backpressure.
 *
 * <h2>Thread safety</h2>
 * {@link ConcurrentHashMap#computeIfAbsent} ensures only one connection is
 * created per node even under concurrent routing pressure.
 *
 * <h2>Interview angle</h2>
 * "Why not route on the server side?" — Redis Cluster uses client-side routing
 * with MOVED redirects to keep the server hot path simple and avoid an extra
 * network hop for the common case (client has an up-to-date slot map). This
 * mirrors that design.
 */
public class ClusterRouter implements Closeable {

    private static final Logger log = LoggerFactory.getLogger(ClusterRouter.class);

    private final ConsistentHashRing ring;
    private final Map<String, NodeInfo> nodeRegistry;

    /** One persistent connection per node ID. */
    private final Map<String, NodeConnection> connections = new ConcurrentHashMap<>();

    public ClusterRouter(ConsistentHashRing ring, Map<String, NodeInfo> nodeRegistry) {
        this.ring = ring;
        this.nodeRegistry = nodeRegistry;
    }

    // ── Routing ───────────────────────────────────────────────────────────────

    /**
     * Route a command to the node that owns the given key.
     *
     * @param key     the key being operated on (used for ring lookup)
     * @param command the raw inline command to forward (e.g. {@code "SET foo bar"})
     * @return the raw RESP response from the owning node
     * @throws IOException if the connection to the target node fails
     */
    public String route(String key, String command) throws IOException {
        String nodeId = ring.getNode(key);
        if (nodeId == null) {
            return "-ERR cluster has no nodes\r\n";
        }
        NodeInfo nodeInfo = nodeRegistry.get(nodeId);
        if (nodeInfo == null) {
            return "-ERR node " + nodeId + " not found in registry\r\n";
        }
        NodeConnection conn = getOrCreateConnection(nodeInfo);
        log.debug("Routing '{}' to node {} ({})", command, nodeId, nodeInfo.address());
        return conn.send(command);
    }

    /**
     * Return the node ID that owns the given key, according to the current ring.
     * Used by per-node handlers to check whether a key belongs to them.
     */
    public String ownerOf(String key) {
        return ring.getNode(key);
    }

    // ── MOVED response factory ────────────────────────────────────────────────

    /**
     * Build a MOVED error response in Redis Cluster format.
     *
     * <p>Format: {@code -MOVED <nodeId> <host>:<port>}
     *
     * <p>A per-node handler emits this when a client directly connects to a node
     * that doesn't own the requested key. The client should retry against the
     * indicated node.
     *
     * @param nodeId   the ID of the node that actually owns the key
     * @param nodeInfo the connection info for that node
     * @return the MOVED error string (includes trailing {@code \r\n})
     */
    public static String movedResponse(String nodeId, NodeInfo nodeInfo) {
        return "-MOVED " + nodeId + " " + nodeInfo.address() + "\r\n";
    }

    // ── Connection management ─────────────────────────────────────────────────

    private NodeConnection getOrCreateConnection(NodeInfo nodeInfo) throws IOException {
        try {
            return connections.computeIfAbsent(nodeInfo.id(), id -> {
                try {
                    log.info("Opening connection to cluster node {}", nodeInfo);
                    return new NodeConnection(nodeInfo);
                } catch (IOException e) {
                    throw new UncheckedIOException(e);
                }
            });
        } catch (UncheckedIOException e) {
            throw e.getCause();
        }
    }

    @Override
    public void close() {
        connections.values().forEach(c -> {
            try { c.close(); } catch (IOException ignored) {}
        });
        connections.clear();
    }

    // ── Inner class: single TCP connection to a peer shard node ──────────────

    /**
     * Thin wrapper around a Socket that provides line-oriented send/receive.
     * Not thread-safe — each router instance uses one connection per node and
     * the router itself is called from one routing thread at a time.
     */
    static class NodeConnection implements Closeable {

        private final Socket socket;
        private final PrintWriter out;
        private final BufferedReader in;

        NodeConnection(NodeInfo nodeInfo) throws IOException {
            this.socket = new Socket(nodeInfo.host(), nodeInfo.port());
            this.socket.setSoTimeout(2_000);   // 2 s read timeout
            this.out = new PrintWriter(
                    new OutputStreamWriter(socket.getOutputStream(), StandardCharsets.UTF_8), true);
            this.in = new BufferedReader(
                    new InputStreamReader(socket.getInputStream(), StandardCharsets.UTF_8));
        }

        /** Send a command line and return the first response line. */
        String send(String command) throws IOException {
            out.println(command);
            return in.readLine();
        }

        @Override
        public void close() throws IOException {
            socket.close();
        }
    }
}
